---
name: runner-build

on:
  push:
    branches:
      - main
    paths:
      - "runner/Dockerfile"

jobs:        
  BuildRunner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_OWNER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_OWNER }}

      - name: Push image
        run: |
          IMAGE="pixiake/actions-runner:latest"
          docker buildx build --platform linux/amd64 --push -f runner/Dockerfile -t $IMAGE .
          echo "Push $IMAGE success!"
  
