---
name: sync

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          sudo apt update -y
          sudo apt install skopeo -y

      - run: |
          FILE=$(git diff --name-only HEAD~1)
          
          if [ -z "$FILE" ]; then
            echo "No rules file changed"
            exit 0
          else
              while IFS= read -r line; do
                if [[ $line == *" => "* ]]; then
                    IFS="=>" read -r -a fields <<< "$line"
                    
                    src=${fields[0]}
                    src=${src##*( )}
                    src=${src%%*( )}
        
                    dst=${fields[1]}
                    dst=${dst##*( )}
                    dst=${dst%%*( )}
        
                    echo "skopeo copy docker://${src}  docker://${dst} --all"
                fi
              done < "$file_path"
          fi