---
name: imagesync

on:
  issues:
    types:
      - "opened"
      - "reopened"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get issue content
        run: |
          echo "${{ github.event.issue.body }}" > issue-${{ github.event.issue.number }}

      - name: Create Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: issue-${{ github.event.issue.number }}
          title: "Adding issue content"
          body: |
            This pull request adds the content of the issue to a file.      
          delete-branch: true

      - name: Send WeChat Notification
        if: always()
        env:
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          STATUS: ${{ steps.create_pull_request.outcome }}
        run: |
          if [[ $STATUS == 'success' ]]; then
             message="收到新的镜像同步请求，请及时处理：[pr-${{ steps.create_pull_request.outputs.pull-request-number }}](${{ steps.create_pull_request.outputs.pull-request-url }})，关联[issue-${{ github.event.issue.number }}](https://github.com/CloudNativeTools/automated-scripts/issues/${{ github.event.issue.number }})"
          else
             message="[issue-${{ github.event.issue.number }}](https://github.com/CloudNativeTools/automated-scripts/issues/${{ github.event.issue.number }}) 镜像同步请求提交失败"
          fi
          curl "${WECHAT_WEBHOOK}" \
              -H 'Content-Type: application/json' \
              -d '
              {
                  "msgtype": "markdown",
                  "markdown": {
                    "content": "'"$message"'"
                  }
              }'
