---
name: imagesync

on:
  issues:
    types:
      - "opened"
      - "reopened"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          echo "${{ github.event.issue.body }}" > ${{ github.event.issue.number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: issue-${{ github.event.issue.number }}
          title: "Adding issue content"
          body: |
            This pull request adds the content of the issue to a file.      
          delete-branch: true
          assignees: pixiake
          reviewers: pixiake


