---
name: imagesync

on:
  issues:
    types:
      - "opened"
      - "reopened"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get issue content
        run: |
          echo "${{ github.event.issue.body }}" > issue-${{ github.event.issue.number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: issue-${{ github.event.issue.number }}
          title: "Adding issue content"
          body: |
            This pull request adds the content of the issue to a file.      
          delete-branch: true
          assignees: pixiake
          reviewers: pixiake

      - name: Send WeChat Notification
        env:
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          STATUS: ${{ job.status }}
        run: |
          if [[ $STATUS == 'success' ]]; then
             message="[issue-${{ github.event.issue.number }}](https://github.com/CloudNativeTools/automated-scripts/issues/${{ github.event.issue.number }}) 中镜像已同步"
          else
             message="[issue-${{ github.event.issue.number }}](https://github.com/CloudNativeTools/automated-scripts/issues/${{ github.event.issue.number }}) 中镜像同步失败"

          curl "WECHAT_WEBHOOK" \
              -H 'Content-Type: application/json' \
              -d '
              {
                  "msgtype": "markdown",
                  "markdown": {
                    "content": "$message"
                  }
              }'

