---
name: imagesync

on:
  issues:
    types:
      - "opened"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          echo echo "${{ github.event.issue.body }}" > issue.txt
          git config --global user.email "ci-bot@kubesphere.io"
          git config --global user.name "ci-bot"

      - name: Create Branch
        run: git checkout -b issue-${{ github.event.issue.number }}
  
      - name: Add Changes to Branch
        run: git add issue.txt
  
      - name: Commit Changes
        run: git commit -m "Add issue content"
  
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: issue-${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: issue-${{ github.event.issue.number }}
          title: "Adding issue content"
          body: |
            This pull request adds the content of the issue to a file.      


